org: tblackford
app: us-election-history
service: cartographer-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  map:
    handler: handler.get_map
    events:
      - http:
          path: map/{year}
          method: get
          request:
            parameters:
              paths:
                year: true
